### ISSUE TITLE
[question] Page localization.

### ISSUE THREAD

**Issue by BeyondLimitation** [AppImage/AppImageSpec#11]
Hi, thanks for reading this.
Well, i'm practicing making **AppImage**, and understanding docs.

But one day i thought "what if a person whose English skill are bad?" and this person will suffer from reading.

So what if someone translate docs?
Can someone's translation be accepted?

Thanks for reading.

**Comment by probonopd** [comment]
Hi @BeyondLimitation, thanks for your question. Since AppImageKit is mainly for developers who want to develop AppImages of their software, we assume that the main language is English. It would be a lot of work to translate everything not just once, but keep the translations updated all the time.

I could imagine that we translate the part "how to make executable and run an AppImage", but not all the developer documentation.

Would you volunteer for Korean?

**Comment by BeyondLimitation** [comment]
@probonopd Thanks for answer!
