### ISSUE TITLE
Is .desktop mandatory in `AppDir/usr/share/applications`  too or just in AppDir root?

### ISSUE THREAD

**Issue by brunvonlope** [AppImage/AppImageSpec#49]
This line says:

https://github.com/AppImage/AppImageSpec/blob/f1631a2ab03703932ec31b6ec6cb1b119d6dcbdd/draft.md?plain=1#L146

However, if we don't ship the desktop file in the "usual" place (`AppDir/usr/share/applications`), `appstreamcli` (which is called by appimagetool) fails:

```
Trying to validate AppStream information with the appstreamcli tool
In case of issues, please refer to https://github.com/ximion/appstream
org.gimp.GIMP.Continuous.appdata.xml
  W: org.gimp.GIMP.Continuous:~: desktop-file-not-found



✘ Validation failed: warnings: 1, pedantic: 2
```

**Comment by probonopd** [comment]
* A desktop file is not mandatory
* But according to the AppImageSpec, the AppDir **SHOULD** contain exactly one `$APPNAME.desktop` file in its root directory with `$APPNAME` being the name of the payload application. This can be used by desktop integration tools to know some metadata about the main application (since there could be multiple ones in the AppDir)
* And if you want to use AppStream, you also need one in `usr/share/applications` because that is where AppStream needs it. Remember that there could be more than one in this location; which is why point 2 still holds

**Comment by brunvonlope** [comment]
Thanks, I will do a symlink, then.

Closing as clarified.

**Comment by TheAssassin** [comment]
@probonopd that's not entirely true. The original ancient AppDir spec from ROX Filer does not mandate them. However, virtually any AppImage related tool mandates their existence. Cf. https://docs.appimage.org/reference/appdir.html. Please refer to such reference documents.

**Comment by probonopd** [comment]
...which is why I wrote 

> A desktop file is **not** mandatory

;)
